name: C/C++ CI



on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: install correct version of mingw
      run | 
         choco uninstall mingw --force
         choco uninstall strawberryperl --force
    
    - uses: numworks/setup-msys2@v1
      with: 
           msystem: MINGW32
           

    - uses: actions/checkout@v2
    - name: configure
      run: ./qt.config.bat 5.9 5.9.9
    - name: build
      run: ./qt.make.bat 5.9 5.9.9