name: C/C++ CI



on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
       ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - name: uninstall uncorrect version of mingw
      run: | 
         choco uninstall mingw --force
         choco uninstall strawberryperl --force
    
    - name: install correct version of mingw
      uses:  msys2/setup-msys2@v2
      with: 
           msystem: MINGW32
           

    - uses: actions/checkout@v2
    - name: configure-qt
      run: ./qt.config.bat 5.9 5.9.9
    - name: make-qt
      run: ./qt.make.bat 5.9 5.9.9