name: C/C++ CI

env:
 QT_VERSION: "5.12.7"
 MINGW_VERSION: "win32_mingw73"
 MINGW_PATH: "mingw73_32"



on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
  - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: install correct version of mingw
      run: choco uninstall mingw --force ; choco uninstall strawberryperl --force;
    - uses: msys2/setup-msys2@v2
      with: 
           msystem: MINGW32
           

    - uses: actions/checkout@v2
    - name: configure
      run: ./qt_5.12.10.build.bat
