name: C/C++ CI



on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: msys2/setup-msys2@v2
      with: 
           msystem: MINGW32
           

    - uses: actions/checkout@v2
    - name: configure
      run: ./qt.config.bat 5.1 5.1.0
    - name: build
      run: ./qt.make.bat  5.1 5.1.0